---
sidebar: sidebar 
permalink: trident-docker/volumes-docker.html 
keywords: create volumes, Trident, trident for docker, docker, docker volume 
summary: '볼륨을 생성하려면 필요에 따라 지정된 Trident 드라이버 이름으로 표준 `docker volume` 명령을 사용합니다.' 
---
= 볼륨 작업
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
필요한 경우 Trident 드라이버 이름을 지정한 표준 명령을 사용하여 볼륨을 쉽게 생성, 클론 복제 및 제거할 수 `docker volume` 있습니다.



== 볼륨을 생성합니다

* 기본 이름을 사용하여 드라이버로 볼륨을 생성합니다.
+
[listing]
----
docker volume create -d netapp --name firstVolume
----
* 특정 Trident 인스턴스를 사용하여 볼륨 생성:
+
[listing]
----
docker volume create -d ntap_bronze --name bronzeVolume
----
+

NOTE: 지정하지 않은 경우 link:volume-driver-options.html["옵션"^], 드라이버 기본값이 사용됩니다.

* 기본 볼륨 크기를 재정의합니다. 다음 예를 참조하여 드라이버로 20GiB 볼륨을 생성합니다.
+
[listing]
----
docker volume create -d netapp --name my_vol --opt size=20G
----
+

TIP: 볼륨 크기는 옵션 단위(예: 10G, 20GB, 3TiB)가 포함된 정수 값이 포함된 문자열로 표시됩니다. 단위를 지정하지 않으면 기본값은 G입니다 크기 단위는 2(B, KiB, MiB, GiB, TiB) 또는 10(B, KB, MB, GB, TB)의 거듭제곱으로 표현될 수 있습니다. 단축 단위는 2의 거듭제곱을 사용합니다(G=GiB, T=TiB,…).





== 볼륨을 제거합니다

* 다른 Docker 볼륨과 마찬가지로 볼륨을 제거합니다.
+
[listing]
----
docker volume rm firstVolume
----
+

IMPORTANT: '솔드파이어-SAN' 드라이버를 사용할 때 위의 예에서는 볼륨을 삭제하고 삭제합니다.



Trident for Docker를 업그레이드하려면 아래 단계를 수행하십시오.



== 볼륨의 클론을 생성합니다

 `ontap-san`, , `solidfire-san` 및 를 `gcp-cvs storage drivers` 사용할 때 `ontap-nas` Trident에서 볼륨 클론 복제를 수행할 수 있습니다. 또는 `ontap-nas-economy` 드라이버를 사용할 때는 `ontap-nas-flexgroup` 복제가 지원되지 않습니다. 기존 볼륨에서 새 볼륨을 생성하면 새 스냅샷이 생성됩니다.

* 볼륨을 검사하여 스냅샷을 열거합니다.
+
[listing]
----
docker volume inspect <volume_name>
----
* 기존 볼륨에서 새 볼륨을 생성합니다. 이렇게 하면 새 스냅샷이 생성됩니다.
+
[listing]
----
docker volume create -d <driver_name> --name <new_name> -o from=<source_docker_volume>
----
* 볼륨의 기존 스냅샷에서 새 볼륨을 생성합니다. 새 스냅샷은 생성하지 않습니다.
+
[listing]
----
docker volume create -d <driver_name> --name <new_name> -o from=<source_docker_volume> -o fromSnapshot=<source_snap_name>
----




=== 예

[listing]
----
docker volume inspect firstVolume

[
    {
        "Driver": "ontap-nas",
        "Labels": null,
        "Mountpoint": "/var/lib/docker-volumes/ontap-nas/netappdvp_firstVolume",
        "Name": "firstVolume",
        "Options": {},
        "Scope": "global",
        "Status": {
            "Snapshots": [
                {
                    "Created": "2017-02-10T19:05:00Z",
                    "Name": "hourly.2017-02-10_1505"
                }
            ]
        }
    }
]

docker volume create -d ontap-nas --name clonedVolume -o from=firstVolume
clonedVolume

docker volume rm clonedVolume
docker volume create -d ontap-nas --name volFromSnap -o from=firstVolume -o fromSnapshot=hourly.2017-02-10_1505
volFromSnap

docker volume rm volFromSnap
----


== 외부에서 생성된 볼륨에 액세스합니다

파티션이 없고 파일 시스템이 Trident에서 지원되는 경우(예: Trident를 통해 형식 지정된 `/dev/sdc1` 블록 장치에 액세스할 수 없음) Trident * only * 를 사용하여 컨테이너를 통해 외부에서 생성된 블록 장치(또는 해당 클론) `ext4`에 액세스할 수 있습니다.
