---
settings:
  name: Trident
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  pdf:
    allow-incremental: false
  rss_page: trident-rn.html
  versions:
  - version-number: '25.02'
    url: "/trident"
  - version-number: '24.10'
    url: "/trident-2410"
  - version-number: '24.06'
    url: "/trident-2406"
  - version-number: '24.02'
    url: "/trident-2402"
  - version-number: '23.10'
    url: "/trident-2310"
  - version-number: '23.07'
    url: "/trident-2307"
  - version-number: '23.04'
    url: "/trident-2304"
  - version-number: '23.01'
    url: "/trident-2301"
  - version-number: '22.10'
    url: "/trident-2210"
  - version-number: '22.07'
    url: "/trident-2207"
  - version-number: '22.04'
    url: "/trident-2204"
  langs: ko-kr,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,zh-cn,zh-tw
sidebar:
  entries:
  - title: Trident 문서
    url: "/index.html"
  - title: 릴리스 정보
    entries:
    - title: 새로운 소식
      url: "/trident-rn.html"
    - title: 이전 버전
      url: "/earlier-versions.html"
    - title: 알려진 문제
      url: "/known-issues.html"
  - section: trident-get-started
  - section: trident-install
  - section: trident-use
  - section: trident-managing-k8s
  - section: trident-docker
  - section: trident-reco
  - section: trident-protect
  - title: 블로그 게시물
    url: "/blog-posts.html"
  - title: 지식 및 지원
    entries:
    - title: FAQ 를 참조하십시오
      url: "/faq.html"
    - title: 문제 해결
      url: "/troubleshooting.html"
    - title: 도움을 받으십시오
      url: "/get-help.html"
  - section: trident-reference
  - title: 법적 고지
    url: "/legal-notices.html"
product-family:
  name: Trident
  repo: astra-family
