---
sidebar: sidebar 
permalink: trident-use/fcp.html 
keywords: storage class, manage storage class, storage classes, kubernetes storage classes, worker node, iscsi, scsi, scsi over fc, fibre channel, fcp, kubernetes clusters, self-healing, healing. 
summary:  
---
= 파이버 채널(FC) 지원
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이제 Trident와 함께 파이버 채널(FC) 프로토콜을 사용하여 ONTAP 시스템에서 스토리지 리소스를 프로비저닝하고 관리할 수 있습니다.

*FC(SCSI over Fibre Channel)는 Trident 24.10 릴리스의 기술 미리 보기 기능입니다.*

파이버 채널은 뛰어난 성능, 안정성 및 확장성으로 인해 엔터프라이즈 스토리지 환경에서 널리 채택되는 프로토콜입니다. 스토리지 장치에 강력하고 효율적인 통신 채널을 제공하여 데이터를 빠르고 안전하게 전송할 수 있습니다. Fibre Channel을 통한 SCSI를 사용하면 기존 SCSI 기반 스토리지 인프라를 활용하면서 Fibre Channel의 고성능 및 장거리 기능을 활용할 수 있습니다. 스토리지 리소스를 통합하고 짧은 지연 시간으로 대량의 데이터를 처리할 수 있는 확장 가능하고 효율적인 SAN(Storage Area Network)을 만들 수 있습니다.

Trident에서 FC 기능을 사용하여 다음을 수행할 수 있습니다.

* 배포 사양을 사용하여 PVC를 동적으로 프로비저닝합니다.
* 볼륨 스냅샷을 촬영하고 스냅샷에서 새 볼륨을 생성합니다.
* 기존 FC-PVC를 복제합니다.
* 이미 구축한 볼륨의 크기를 조정합니다.




== 필수 구성 요소

FC에 필요한 네트워크 및 노드 설정을 구성합니다.



=== 네트워크 설정

. 대상 인터페이스의 WWPN을 가져옵니다. 자세한 내용은 을 https://docs.netapp.com/us-en/ontap-cli//network-interface-show.html["네트워크 인터페이스가 표시됩니다"^] 참조하십시오.
. 이니시에이터(호스트)의 인터페이스에 대한 WWPN을 가져옵니다.
+
해당 호스트 운영 체제 유틸리티를 참조하십시오.

. 호스트와 대상의 WWPN을 사용하여 FC 스위치에서 조닝을 구성합니다.
+
자세한 내용은 존경하는 스위치 공급업체 문서를 참조하십시오.

+
자세한 내용은 다음 ONTAP 설명서를 참조하십시오.

+
** https://docs.netapp.com/us-en/ontap/san-config/fibre-channel-fcoe-zoning-concept.html["파이버 채널 및 FCoE 조닝 개요"^]
** https://docs.netapp.com/us-en/ontap/san-config/configure-fc-nvme-hosts-ha-pairs-reference.html["FC 및 AMP, FC-NVMe SAN 호스트를 구성하는 방법"^]






=== 작업자 노드를 준비합니다

Kubernetes 클러스터의 모든 작업자 노드는 Pod용으로 프로비저닝된 볼륨을 마운트할 수 있어야 합니다. FC에 대한 작업자 노드를 준비하려면 필요한 도구를 설치해야 합니다.

.FC 툴을 설치합니다
운영 체제의 명령을 사용하여 FC 툴을 설치합니다.

* FC PVS와 함께 RHEL/RedHat CoreOS를 실행하는 작업자 노드를 사용하는 경우 `discard` 인라인 공간 재확보를 수행하려면 StorageClass에 mount옵션을 지정합니다. 을 https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_file_systems/discarding-unused-blocks_managing-file-systems["RedHat 설명서"^]참조하십시오.


[role="tabbed-block"]
====
.RHEL 8+
--
. 다음 시스템 패키지를 설치합니다.
+
[listing]
----
sudo yum install -y lsscsi device-mapper-multipath
----
. 다중 경로 설정:
+
[listing]
----
sudo mpathconf --enable --with_multipathd y --find_multipaths n
----
+

NOTE: etc/multipath.conf에 debrofs 아래에 find_multiprohs no가 포함되어 있는지 확인합니다.

. 가 `multipathd` 실행 중인지 확인합니다.
+
[listing]
----
sudo systemctl enable --now multipathd
----


--
.우분투
--
. 다음 시스템 패키지를 설치합니다.
+
[listing]
----
sudo apt-get install -y lsscsi sg3-utils multipath-tools scsitools
----
. 다중 경로 설정:
+
[listing]
----
sudo tee /etc/multipath.conf <<-EOF
defaults {
    user_friendly_names yes
    find_multipaths no
}
EOF
sudo systemctl enable --now multipath-tools.service
sudo service multipath-tools restart
----
+

NOTE: etc/multipath.conf에 debrofs 아래에 find_multiprohs no가 포함되어 있는지 확인합니다.

. 가 활성화되어 있고 실행 중인지 `multipath-tools` 확인합니다.
+
[listing]
----
sudo systemctl status multipath-tools
----


--
====


== 백엔드 구성을 생성합니다

드라이버 및 `fcp` sanType에 대한 Trident 백엔드를 `ontap-san` 생성합니다.

참조:

* link:..trident-use/ontap-san-prep.html["ONTAP SAN 드라이버를 사용하여 백엔드를 구성할 준비를 합니다"]
* link:..trident-use/ontap-san-examples.html["ONTAP SAN 구성 옵션 및 예"^]


.FC를 사용한 백엔드 구성 예
[listing]
----
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-ontap-san
spec:
  version: 1
  backendName: ontap-san-backend
  storageDriverName: ontap-san
  managementLIF: 10.0.0.1
  sanType: fcp
  svm: trident_svm
  credentials:
    name: backend-tbc-ontap-san-secret
----


== 스토리지 클래스를 생성합니다

자세한 내용은 다음을 참조하십시오.

* link:..trident-docker/stor-config.html["스토리지 구성 옵션"^]


.스토리지 클래스 예
[listing]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fcp-sc
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-san"
  protocol: "fcp"
  storagePool: "aggr1"
allowVolumeExpansion: True
----