---
sidebar: sidebar 
permalink: trident-use/trident-fsx.html 
keywords: Amazon FSx for NetApp ONTAP, FSx for ONTAP, deploy Trident, integrate Trident, Trident 
summary: 'Trident를 Amazon FSx for NetApp ONTAP와 함께 사용하면 Amazon EKS(Elastic Kubernetes Service)에서 실행되는 Kubernetes 클러스터가 ONTAP에서 지원하는 블록 및 파일 영구 볼륨을 프로비저닝할 수 있습니다.' 
---
= Trident를 Amazon FSx for NetApp ONTAP와 함께 사용해 보십시오
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["NetApp ONTAP용 Amazon FSx"^] NetApp ONTAP 스토리지 운영 체제가 제공하는 파일 시스템을 실행하고 실행할 수 있도록 완벽하게 관리되는 AWS 서비스입니다. ONTAP용 FSX를 사용하면 익숙한 NetApp 기능, 성능 및 관리 기능을 활용하는 동시에, AWS에 데이터를 저장하는 데 따른 단순성, 민첩성, 보안, 확장성을 활용할 수 있습니다. ONTAP용 FSX는 ONTAP 파일 시스템 기능 및 관리 API를 지원합니다.

Amazon FSx for NetApp ONTAP 파일 시스템을 Trident와 통합하여 Amazon EKS(Elastic Kubernetes Service)에서 실행되는 Kubernetes 클러스터가 ONTAP에서 지원하는 블록 및 파일 영구 볼륨을 프로비저닝할 수 있도록 할 수 있습니다.

파일 시스템은 Amazon FSx의 주요 리소스이며, 이는 사내 ONTAP 클러스터와 유사합니다. 각 SVM 내에서 파일 시스템에 파일과 폴더를 저장하는 데이터 컨테이너인 하나 이상의 볼륨을 생성할 수 있습니다. Amazon FSx for NetApp ONTAP은 클라우드에서 관리형 파일 시스템으로 제공됩니다. 새로운 파일 시스템 유형을 * NetApp ONTAP * 라고 합니다.

Trident를 Amazon FSx for NetApp ONTAP와 함께 사용하면 Amazon EKS(Elastic Kubernetes Service)에서 실행되는 Kubernetes 클러스터가 ONTAP에서 지원하는 블록 및 파일 영구 볼륨을 프로비저닝할 수 있습니다.



== 요구 사항

link:../trident-get-started/requirements.html["Trident 요구사항"]FSx for ONTAP를 Trident와 통합하려면 다음이 필요합니다.

* kubbtl이 설치된 기존 Amazon EKS 클러스터 또는 자체 관리 Kubernetes 클러스터
* 클러스터의 작업자 노드에서 연결할 수 있는 NetApp ONTAP 파일 시스템용 기존 Amazon FSx 및 SVM(Storage Virtual Machine).
* 에 대해 준비된 작업자 노드입니다 link:worker-node-prep.html["NFS 또는 iSCSI"].
+

NOTE: Amazon Linux 및 Ubuntu에 필요한 노드 준비 단계를 따라야 합니다 https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AMIs.html["Amazon Machine Images(아마존 머신 이미지)"^] (AMI) EKS AMI 유형에 따라 다릅니다.





== 고려 사항

* SMB 볼륨:
+
** SMB 볼륨은 를 사용하여 지원됩니다 `ontap-nas` 드라이버만 해당.
** Trident EKS 애드온에서는 SMB 볼륨이 지원되지 않습니다.
** Trident는 Windows 노드에서만 실행되는 Pod에 마운트된 SMB 볼륨을 지원합니다. 자세한 내용은 을 link:../trident-use/trident-fsx-storage-backend.html#prepare-to-provision-smb-volumes["SMB 볼륨 프로비저닝을 위한 준비"] 참조하십시오.


* Trident 24.02 이전에는 자동 백업이 활성화된 Amazon FSx 파일 시스템에서 생성된 볼륨을 Trident에서 삭제할 수 없었습니다. Trident 24.02 이상에서 이 문제를 방지하려면 `fsxFilesystemID` AWS FSx for ONTAP의 백엔드 구성 파일에, AWS, `apikey` AWS `apiRegion` 및 AWS를 `secretKey` 지정합니다.
+

NOTE: Trident에 IAM 역할을 지정하는 경우, `apiKey` 및 `secretKey` 필드를 명시적으로 Trident에 지정하지 않아도 됩니다 `apiRegion`. 자세한 내용은 을 link:../trident-use/trident-fsx-examples.html["ONTAP 구성 옵션 및 예제용 FSX"]참조하십시오.





== 인증

Trident는 두 가지 인증 모드를 제공합니다.

* 자격 증명 기반(권장): 자격 증명을 AWS Secrets Manager에 안전하게 저장합니다. 파일 시스템 또는 SVM에 구성된 사용자를 사용할 수 있습니다 `fsxadmin` `vsadmin` .
+

WARNING: Trident은 SVM 사용자로 실행하거나 동일한 역할을 가진 다른 이름의 사용자로 실행해야 `vsadmin` 합니다. Amazon FSx for NetApp ONTAP에는 `fsxadmin` ONTAP 클러스터 사용자를 제한적으로 대체하는 사용자가 `admin` 있습니다. Trident와 함께 를 사용하는 `vsadmin` 것이 좋습니다.

* 인증서 기반: Trident은 SVM에 설치된 인증서를 사용하여 FSx 파일 시스템의 SVM과 통신합니다.


인증 활성화에 대한 자세한 내용은 드라이버 유형에 대한 인증을 참조하십시오.

* link:ontap-nas-prep.html["ONTAP NAS 인증"]
* link:ontap-san-prep.html["ONTAP SAN 인증"]




== 테스트된 아마존 머신 이미지(AMI)

EKS 클러스터는 다양한 운영 체제를 지원하지만 AWS는 컨테이너 및 EKS에 대해 특정 AMI(Amazon Machine Images)를 최적화했습니다. 다음 AMI는 NetApp Trident 25.02에서 테스트되었습니다.

|===


| 아미 | NAS | NAS - 경제형 | iSCSI | iSCSI 경제 


| AL2023_x86_64_STANDARD를 참조하십시오 | 예 | 예 | 예 | 예 


| AL2_x86_64를 참조하십시오 | 예 | 예 | 예 * | 예 * 


| BOTTLEROCKET_x86_64를 참조하십시오 | 예** | 예 | 해당 없음 | 해당 없음 


| AL2023_ARM_64_STANDARD를 참조하십시오 | 예 | 예 | 예 | 예 


| AL2_ARM_64를 참조하십시오 | 예 | 예 | 예 * | 예 * 


| BOTTLEROCKET_ARM_64를 참조하십시오 | 예** | 예 | 해당 없음 | 해당 없음 
|===
* * 노드를 재시작하지 않고는 PV를 삭제할 수 없습니다.
* ** Trident 버전 25.02에서는 NFSv3와 작동하지 않습니다.



NOTE: 원하는 AMI가 여기에 나열되지 않은 경우 지원되지 않는다는 의미는 아닙니다. 단순히 테스트를 거치지 않았음을 의미합니다. 이 목록은 AMI가 작동하는 방법에 대한 가이드 역할을 합니다.

* 다음을 사용하여 수행한 테스트:

* EKS 버전: 1.32
* 설치 방법: Helm 25.06 및 AWS 추가 기능 25.06
* NAS의 경우 NFSv3과 NFSv4.1이 모두 테스트되었습니다.
* SAN 전용 iSCSI는 테스트되었으며 NVMe-oF는 테스트되지 않았습니다.


* 수행된 테스트 *:

* 생성 : 저장 클래스, PVC, POD
* 삭제: Pod, PVC(일반, qtree/LUN – 경제성, NAS와 AWS 백업)




== 자세한 내용을 확인하십시오

* https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["NetApp ONTAP용 Amazon FSx 문서"^]
* https://www.netapp.com/blog/amazon-fsx-for-netapp-ontap/["NetApp ONTAP용 Amazon FSx 블로그 게시물"^]

