---
sidebar: sidebar 
permalink: trident-get-started/kubernetes-deploy-helm.html 
keywords: deploy, Trident, operator, helm, helm chart, configuration, values, standard, registry 
summary: Trident 연산자를 배포하고 Helm을 사용하여 Trident를 설치할 수 있습니다. 이 프로세스는 Trident에 필요한 컨테이너 이미지가 개인 레지스트리에 저장되지 않은 설치에 적용됩니다. 
---
= H제어(표준 모드)를 사용하여 Trident 연산자 배포
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident 연산자를 배포하고 Helm을 사용하여 Trident를 설치할 수 있습니다. 이 프로세스는 Trident에 필요한 컨테이너 이미지가 개인 레지스트리에 저장되지 않은 설치에 적용됩니다. 개인 이미지 레지스트리가 있는 경우 를 link:kubernetes-deploy-helm-mirror.html["오프라인 배포를 위한 프로세스입니다"]사용합니다.



== Trident 25.10에 대한 중요 정보

*Trident에 대한 다음 중요 정보를 읽어야 합니다.*

.<strong> Trident </strong>에 대한 중요 정보입니다
[%collapsible%open]
====
[]
=====
* Kubernetes 1.34가 이제 Trident 에서 지원됩니다. Kubernetes를 업그레이드하기 전에 Trident 업그레이드하세요.
* Trident은 multipath.conf 파일에서 권장 값을 값으로 하여 SAN 환경에서 다중 경로 구성을 엄격히 적용합니다 `find_multipaths: no`.
+
비 경로 다중화 구성 또는 의 사용 `find_multipaths: yes` 또는 `find_multipaths: smart` multipath.conf 파일의 값으로 인해 마운트 오류가 발생합니다. Trident에서 의 사용을 권장했습니다 `find_multipaths: no` 21.07 릴리스 이후.



=====
====


== Trident 연산자를 배포하고 Helm을 사용하여 Trident를 설치합니다

Trident 사용 link:https://artifacthub.io/packages/helm/netapp-trident/trident-operator["Helm 차트"^] Trident 연산자를 구축하고 Trident를 한 번에 설치할 수 있습니다.

검토 link:../trident-get-started/kubernetes-deploy.html["설치 개요"] 설치 사전 요구 사항을 충족하고 환경에 맞는 올바른 설치 옵션을 선택했는지 확인합니다.

.시작하기 전에
또한 link:../trident-get-started/kubernetes-deploy.html#before-you-deploy["구축 사전 요구 사항"] 필요한 것입니다 link:https://v3.helm.sh/["Helm 버전 3"^].

.단계
. Trident Helm 저장소 추가:
+
[listing]
----
helm repo add netapp-trident https://netapp.github.io/trident-helm-chart
----
. 를 `helm install` 사용하고 다음 예제와 같이 배포 이름을 지정합니다. 여기서 는 설치 중인 Trident 버전입니다. `100.2506.0`
+
[listing]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0 --create-namespace --namespace <trident-namespace>
----
+

NOTE: Trident에 대한 네임스페이스를 이미 만든 경우에는 '--create-namespace' 매개 변수가 추가 네임스페이스를 만들지 않습니다.



을 사용할 수 있습니다 `helm list` 이름, 네임스페이스, 차트, 상태, 앱 버전과 같은 설치 세부 정보를 검토하려면 수정본 번호.



== 설치 중에 구성 데이터를 전달합니다

설치 중에 구성 데이터를 전달하는 방법에는 두 가지가 있습니다.

[cols="2"]
|===
| 옵션을 선택합니다 | 설명 


| `--values` (또는 `-f`)  a| 
재정의가 있는 YAML 파일을 지정합니다. 이 옵션은 여러 번 지정할 수 있으며 가장 오른쪽 파일이 우선 적용됩니다.



| `--set`  a| 
명령줄에 overrides를 지정합니다.

|===
예를 들어, 의 기본값을 `debug` 변경하려면 다음 명령을 실행합니다. 여기서 는 설치 중인 Trident의 버전입니다. `100.2506.0`

[listing]
----
helm install <name> netapp-trident/trident-operator --version 100.2506.0  --create-namespace --namespace trident --set tridentDebug=true
----


== 구성 옵션

이 표와 `values.yaml` 제어 차트의 일부인 파일 에는 키 목록과 해당 기본값이 나와 있습니다.

[cols="1,2,3"]
|===
| 옵션을 선택합니다 | 설명 | 기본값 


| `nodeSelector` | POD 할당을 위한 노드 레이블입니다 |  


| `podAnnotations` | 창 주석 |  


| `deploymentAnnotations` | 배포 주석 |  


| `tolerations` | POD 지정에 대한 공차 |  


| `affinity` | POD 할당에 대한 선호도  a| 
[listing]
----
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
              - amd64
            - key: kubernetes.io/os
              operator: In
              values:
              - linux
----

WARNING: values.yaml 파일에서 기본 선호도를 제거하지 마십시오. 사용자 지정 선호도를 제공하려면 기본 선호도를 확장합니다.



| `tridentControllerPluginNodeSelector` | Pod용 추가 노드 선택기 을 참조하십시오 <<컨트롤러 Pod 및 노드 포드 이해>> 를 참조하십시오. |  


| `tridentControllerPluginTolerations` | Pod에 대한 Kubernetes 허용 설정을 재정의합니다. 을 참조하십시오 <<컨트롤러 Pod 및 노드 포드 이해>> 를 참조하십시오. |  


| `tridentNodePluginNodeSelector` | Pod용 추가 노드 선택기 을 참조하십시오 <<컨트롤러 Pod 및 노드 포드 이해>> 를 참조하십시오. |  


| `tridentNodePluginTolerations` | Pod에 대한 Kubernetes 허용 설정을 재정의합니다. 을 참조하십시오 <<컨트롤러 Pod 및 노드 포드 이해>> 를 참조하십시오. |  


| 'imageRegistry'입니다 | , `trident` 및 기타 이미지의 레지스트리를 `trident-operator` 식별합니다. 기본값을 그대로 사용하려면 비워 두십시오. 중요: 전용 리포지토리에 Trident를 설치할 때 스위치를 사용하여 리포지토리 위치를 지정하는 경우 `imageRegistry` 리포지토리 경로에서 를 사용하지 마십시오 `/netapp/`. | `""` 


| `imagePullPolicy` | 에 대한 이미지 풀 정책을 설정합니다 `trident-operator`. | `IfNotPresent` 


| 'imagePullSecrets' | 의 이미지 풀 비밀을 설정합니다 `trident-operator`, `trident`및 기타 이미지. |  


| 쿠벨레트디렉토리 | kubelet 내부 상태의 호스트 위치를 재정의할 수 있습니다. | `"/var/lib/kubelet"` 


| `operatorLogLevel` | Trident 연산자의 로그 수준을 다음으로 설정할 수 있습니다. `trace`, `debug`, `info`, `warn`, `error`, 또는 `fatal`. | `"info"` 


| `operatorDebug` | Trident 연산자의 로그 수준을 디버깅으로 설정할 수 있습니다. | "참"입니다 


| `operatorImage` | 에 대한 이미지를 완전히 재정의할 수 있습니다 `trident-operator`. | `""` 


| `operatorImageTag` | 의 태그를 재정의할 수 있습니다 `trident-operator` 이미지. | `""` 


| `tridentIPv6` | Trident가 IPv6 클러스터에서 작동하도록 설정합니다. | 거짓입니다 


| `tridentK8sTimeout` | 대부분의 Kubernetes API 작업에 대한 기본 30초 시간 초과(0이 아닌 경우 초)를 재정의합니다. | `0` 


| `tridentHttpRequestTimeout` | 에서는 HTTP 요청에 대한 기본 90초 제한 시간을 재정의합니다 `0s` 제한 시간 동안 무한 지속 시간입니다. 음수 값은 허용되지 않습니다. | `"90s"` 


| `tridentSilenceAutosupport` | Trident 정기 AutoSupport 보고를 비활성화할 수 있습니다. | 거짓입니다 


| `tridentAutosupportImageTag` | Trident AutoSupport 컨테이너에 대한 이미지 태그를 재정의할 수 있습니다. | `<version>` 


| `tridentAutosupportProxy` | HTTP 프록시를 통해 Trident AutoSupport 컨테이너를 phone home으로 설정합니다. | `""` 


| `tridentLogFormat` | Trident 로깅 형식 (`text` 또는 `json`)을 설정합니다. | `"text"` 


| `tridentDisableAuditLog` | Trident 감사 로거를 비활성화합니다. | "참"입니다 


| `tridentLogLevel` | Trident의 로그 수준을 , , `debug`, `info`, `warn` `error` 또는 `fatal` 로 설정할 수 `trace` 있습니다. | `"info"` 


| `tridentDebug` | Trident의 로그 수준을 로 설정할 수 `debug` 있습니다. | 거짓입니다 


| `tridentLogWorkflows` | 추적 로깅 또는 로그 억제를 위해 특정 Trident 워크플로우를 사용할 수 있습니다. | `""` 


| `tridentLogLayers` | 추적 로깅 또는 로그 억제를 위해 특정 Trident 계층을 사용할 수 있습니다. | `""` 


| 트리덴티이미지 | Trident에 대한 이미지의 전체 덮어쓰기를 허용합니다. | `""` 


| `tridentImageTag` | Trident에 대한 이미지 태그를 재정의할 수 있습니다. | `""` 


| `tridentProbePort` | Kubernetes 활성/준비 프로브에 사용되는 기본 포트를 재정의할 수 있습니다. | `""` 


| `windows` | Windows 작업자 노드에 Trident를 설치할 수 있습니다. | 거짓입니다 


| `enableForceDetach` | 힘 분리 기능을 활성화합니다. | 노드 상태 점검(NHC) 연산자와 통합하여 강제 분리 프로세스를 자동화할 수 있습니다. 자세한 내용은 다음을 참조하세요.link:../trident-reco/force-detach.html["Trident 사용하여 상태 저장 애플리케이션의 장애 조치 자동화"] . 


| 거짓입니다 | `excludePodSecurityPolicy` | 운영자 POD 보안 정책을 생성할 수 없습니다. 


| 거짓입니다 | `cloudProvider` | 를 로 설정합니다 `"Azure"` AKS 클러스터에서 관리되는 ID 또는 클라우드 ID를 사용하는 경우 EKS 클러스터에서 클라우드 ID를 사용하는 경우 "AWS"로 설정합니다. 


| `""` | `cloudIdentity` | AKS 클러스터에서 클라우드 ID를 사용할 때 워크로드 ID("Azure.workload.identity/client-id: xxxxxxxxxxxx-xxxx-xxxx-xxxxxxxxxxxxx")로 설정합니다. EKS 클러스터에서 클라우드 ID를 사용할 때 AWS IAM 역할("'eks.amazonaws.com/role-arn: arn:AWS:IAM::123456:role/Trident-role'")로 설정합니다. 


| `""` | `iscsiSelfHealingInterval` | iSCSI 자동 복구가 호출되는 간격입니다. 


| `5m0s` | `iscsiSelfHealingWaitTime` | iSCSI 자체 복구가 로그아웃과 후속 로그인을 수행하여 부실 세션을 해결하려는 시도를 시작한 이후의 기간입니다. 


| `7m0s` | `nodePrep` | Trident 지정된 데이터 저장 프로토콜을 사용하여 볼륨을 관리하도록 Kubernetes 클러스터의 노드를 준비할 수 있도록 합니다.  *현재, `iscsi` 지원되는 유일한 값입니다.*  참고: OpenShift 4.19부터 이 기능을 지원하는 최소 Trident 버전은 25.06.1입니다. 


|  | `enableConcurrency`  a| 
향상된 처리량을 위해 동시 Trident 컨트롤러 작업이 가능합니다.


NOTE: *기술 미리보기*: 이 기능은 실험적이며 현재 ONTAP-NAS(NFS만 해당) 및 ONTAP-SAN(통합 ONTAP 9의 NVMe) 드라이버를 사용한 제한된 병렬 워크플로를 지원합니다. 또한, ONTAP-SAN 드라이버(통합 ONTAP 9의 iSCSI 및 FCP 프로토콜)에 대한 기존 기술 미리보기도 지원합니다.



| 거짓 | `k8sAPIQPS`  a| 
Kubernetes API 서버와 통신하는 동안 컨트롤러가 사용하는 초당 쿼리 수(QPS) 제한입니다.  버스트 값은 QPS 값에 따라 자동으로 설정됩니다.



| `100`; 선택 사항 | `resources`  a| 
Trident 컨트롤러, 노드 및 운영자 포드에 대한 Kubernetes 리소스 제한 및 요청을 설정합니다. Kubernetes에서 리소스 할당을 관리하기 위해 각 컨테이너와 사이드카에 대한 CPU와 메모리를 구성할 수 있습니다.

리소스 요청 및 제한 구성에 대한 자세한 내용은 다음을 참조하세요.link:https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/["포드 및 컨테이너에 대한 리소스 관리"^] .

[WARNING]
====
* 컨테이너나 필드의 이름을 변경하지 마세요.
* 들여쓰기를 변경하지 마세요. YAML 들여쓰기는 올바른 구문 분석을 위해 중요합니다.


====
[NOTE]
====
* 기본적으로 제한은 적용되지 않습니다. 요청에만 기본값이 있으며, 지정하지 않으면 자동으로 적용됩니다.
* 컨테이너 이름은 포드 사양에 나타나는 대로 나열됩니다.
* 사이드카는 각 주요 컨테이너 아래에 나열되어 있습니다.
* TORC를 확인하세요 `status.CurrentInstallationParams` 현재 적용된 값을 보려면 필드를 클릭하세요.


====


 a| 
[source, yaml]
----
resources:
  controller:
    trident-main:
      requests:
        cpu: 10m
        memory: 80Mi
      limits:
          cpu:
          memory:
    csi-provisioner:
      requests:
        cpu: 2m
        memory: 20Mi
      limits:
        cpu:
        memory:
    csi-attacher:
      requests:
        cpu: 2m
        memory: 20Mi
      limits:
        cpu:
        memory:
    csi-resizer:
      requests:
        cpu: 3m
        memory: 20Mi
      limits:
        cpu:
        memory:
    csi-snapshotter:
      requests:
        cpu: 2m
        memory: 20Mi
      limits:
        cpu:
        memory:
    trident-autosupport:
      requests:
        cpu: 1m
        memory: 30Mi
      limits:
        cpu:
        memory:
  node:
    linux:
      trident-main:
        requests:
          cpu: 10m
          memory: 60Mi
        limits:
          cpu:
          memory:
      node-driver-registrar:
        requests:
          cpu: 1m
          memory: 10Mi
        limits:
          cpu:
          memory:
    windows:
      trident-main:
        requests:
          cpu: 6m
          memory: 40Mi
        limits:
          cpu:
          memory:
      node-driver-registrar:
        requests:
          cpu: 6m
          memory: 40Mi
        limits:
          cpu:
          memory:
      liveness-probe:
        requests:
          cpu: 2m
          memory: 40Mi
        limits:
          cpu:
          memory:
  operator:
    requests:
      cpu: 10m
      memory: 40Mi
    limits:
      cpu:
      memory:
----| `httpsMetrics` | Prometheus 메트릭 엔드포인트에 HTTPS를 활성화합니다. 


| 거짓 | 호스트 네트워크  a| 
Trident 컨트롤러에 대한 호스트 네트워킹을 활성화합니다. 이 기능은 멀티 홈 네트워크에서 프런트엔드와 백엔드 트래픽을 분리할 때 유용합니다.

|===


=== 컨트롤러 Pod 및 노드 포드 이해

Trident는 단일 컨트롤러 Pod와 클러스터의 각 작업자 노드에서 노드 Pod로 실행됩니다. 노드 포드는 Trident 볼륨을 마운트하려는 호스트에서 실행되고 있어야 합니다.

쿠버네티스 link:https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/["노드 선택기"^] 및 link:https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/["관용과 오해"^] 포드를 특정 노드 또는 기본 노드에서 실행하도록 제한하는 데 사용됩니다. ControllerPlugin과 을 사용합니다 `NodePlugin`구속 조건과 덮어쓰기를 지정할 수 있습니다.

* 컨트롤러 플러그인은 스냅샷 및 크기 조정과 같은 볼륨 프로비저닝 및 관리를 처리합니다.
* 노드 플러그인은 스토리지에 노드를 연결하는 작업을 처리합니다.

