= 
:allow-uri-read: 


. (_선택 사항_) 복원할 응용 프로그램의 특정 리소스만 선택해야 하는 경우 특정 레이블로 표시된 리소스를 포함하거나 제외하는 필터링을 추가합니다.
+

NOTE: Trident Protect는 선택한 리소스와의 관계에 따라 일부 리소스를 자동으로 선택합니다. 예를 들어, 영구 볼륨 클레임 리소스를 선택했고 이 리소스에 연결된 Pod가 있는 경우 Trident Protect는 연결된 Pod도 복원합니다.

+
** *resourceFilter.resourceSelectionCriteria*:(필터링에 필요) `Include` resourceMatchers에 정의된 리소스를 포함하거나 제외하려면 또는 을 `Exclude` 사용합니다. 다음 resourceMatchers 매개 변수를 추가하여 포함하거나 제외할 리소스를 정의합니다.
+
*** *resourceFilter.resourceMatchers*: resourceMatcher 개체의 배열입니다. 이 배열에서 여러 요소를 정의하는 경우 해당 요소는 OR 연산으로 일치하고 각 요소(그룹, 종류, 버전) 내의 필드는 AND 연산으로 일치합니다.
+
**** *resourceMatchers[].group*:(_Optional_) 필터링할 리소스의 그룹입니다.
**** * resourceMatchers [].kind *: (_Optional_) 필터링할 리소스의 종류입니다.
**** *resourceMatchers [ ].version*: (_Optional_) 필터링할 리소스의 버전입니다.
**** *resourceMatchers[].names*:(_Optional_) 필터링할 리소스의 Kubernetes metadata.name 필드에 있는 이름입니다.
**** *resourceMatchers [].namespaces *: (_Optional_) 필터링할 리소스의 Kubernetes metadata.name 필드에 있는 네임스페이스입니다.
**** *resourceMatchers [ ].labelSelectors*: (_Optional_) 에 정의된 대로 리소스의 Kubernetes metadata.name 필드에 있는 레이블 선택기 문자열입니다. https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors["Kubernetes 문서"^] 예를 들면 다음과 `"trident.netapp.io/os=linux"`같습니다.
+
예를 들면 다음과 같습니다.

+
[source, yaml]
----
spec:
  resourceFilter:
    resourceSelectionCriteria: "Include"
    resourceMatchers:
      - group: my-resource-group-1
        kind: my-resource-kind-1
        version: my-resource-version-1
        names: ["my-resource-names"]
        namespaces: ["my-resource-namespaces"]
        labelSelectors: ["trident.netapp.io/os=linux"]
      - group: my-resource-group-2
        kind: my-resource-kind-2
        version: my-resource-version-2
        names: ["my-resource-names"]
        namespaces: ["my-resource-namespaces"]
        labelSelectors: ["trident.netapp.io/os=linux"]
----







