---
sidebar: sidebar 
permalink: trident-protect/trident-protect-customize-installation.html 
keywords: customize, trident protect, resource limits, security context constraints, SCC, NetApp AutoSupport, proxy connection, helm, helm chart, helm upgrade 
summary: 특정 요구 사항에 맞게 Trident Protect의 기본 설정을 사용자 지정합니다. 
---
= Trident Protect 설치를 사용자 지정합니다
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Trident Protect의 기본 구성은 사용자 환경의 특정 요구 사항에 맞게 사용자 지정할 수 있습니다.



== Trident Protect 컨테이너 리소스 제한을 지정합니다

Trident Protect를 설치한 후 구성 파일을 사용하여 Trident Protect 컨테이너에 대한 리소스 제한을 지정할 수 있습니다. 리소스 제한을 설정하면 Trident Protect 작업에서 사용되는 클러스터 리소스의 양을 제어할 수 있습니다.

.단계
. 라는 이름의 파일을 `resourceLimits.yaml` 만듭니다.
. 환경 요구 사항에 따라 Trident Protect 컨테이너에 대한 리소스 제한 옵션을 파일에 채웁니다.
+
다음 예제 구성 파일은 사용 가능한 설정을 보여 주며 각 리소스 제한에 대한 기본값을 포함합니다.

+
[source, yaml]
----
---
jobResources:
  defaults:
    limits:
      cpu: 8000m
      memory: 10000Mi
      ephemeralStorage: ""
    requests:
      cpu: 100m
      memory: 100Mi
      ephemeralStorage: ""
  resticVolumeBackup:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  resticVolumeRestore:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  kopiaVolumeBackup:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
  kopiaVolumeRestore:
    limits:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
    requests:
      cpu: ""
      memory: ""
      ephemeralStorage: ""
----
. 파일의 값을 적용합니다 `resourceLimits.yaml`.
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect -f resourceLimits.yaml --reuse-values
----




== 보안 컨텍스트 제약 조건을 사용자 지정합니다

Trident Protect를 설치한 후 구성 파일을 사용하여 Trident Protect 컨테이너에 대한 OpenShift SCC(Security Context Constraint)를 수정할 수 있습니다. 이러한 제약은 Red Hat OpenShift 클러스터의 Pod에 대한 보안 제한을 정의합니다.

.단계
. 라는 이름의 파일을 `sccconfig.yaml` 만듭니다.
. 파일에 SCC 옵션을 추가하고 사용자 환경의 필요에 따라 매개 변수를 수정합니다.
+
다음 예는 SCC 옵션에 대한 매개 변수의 기본값을 보여줍니다.

+
[source, yaml]
----
scc:
  create: true
  name: trident-protect-job
  priority: 1
----
+
다음 표에서는 SCC 옵션에 대한 매개 변수를 설명합니다.

+
|===
| 매개 변수 | 설명 | 기본값 


| 생성 | SCC 자원을 생성할 수 있는지 여부를 결정한다. SCC 리소스는 가 로 설정되어 `true` 있고 Helm 설치 프로세스에서 OpenShift 환경을 식별하는 경우에만 `scc.create` 생성됩니다. OpenShift에서 작동하지 않거나 이 로 설정된 `false` 경우 `scc.create` SCC 리소스가 생성되지 않습니다. | 참 


| 이름 | SCC의 이름을 지정합니다. | Trident-protect-job을 선택합니다 


| 우선 순위 | SCC의 우선 순위를 정의합니다. 우선 순위가 높은 SCC는 값이 낮은 SCC보다 먼저 평가됩니다. | 1 
|===
. 파일의 값을 적용합니다 `sccconfig.yaml`.
+
[source, console]
----
helm upgrade trident-protect netapp-trident-protect/trident-protect -f sccconfig.yaml --reuse-values
----
+
그러면 기본값이 파일에 지정된 값으로 `sccconfig.yaml` 바뀝니다.





== Trident Protect에 대한 NetApp AutoSupport 연결을 구성합니다

연결에 대한 프록시를 구성하여 Trident Protect가 NetApp 지원에 연결하는 방식을 변경하여 지원 번들을 업로드할 수 있습니다. 필요에 따라 보안 또는 비보안 연결을 사용하도록 프록시를 구성할 수 있습니다.

[role="tabbed-block"]
====
.보안 프록시 연결을 구성합니다
--
.단계
. Trident Protect 지원 번들 업로드를 위한 보안 프록시 연결 구성:
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect --set autoSupport.proxy=http://my.proxy.url --reuse-values
----


--
.안전하지 않은 프록시 연결을 구성합니다
--
.단계
. TLS 검증을 건너뛰는 Trident Protect 지원 번들 업로드에 대해 안전하지 않은 프록시 연결을 구성합니다.
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect --set autoSupport.proxy=http://my.proxy.url --set autoSupport.insecure=true --reuse-values
----


--
====


== Trident Protect Pod를 특정 노드로 제한합니다

Kubernetes nodeSelector 노드 선택 제약 조건을 사용하여 노드 레이블을 기준으로 Trident Protect Pod를 실행할 자격이 있는 노드를 제어할 수 있습니다. 기본적으로 Trident Protect는 Linux를 실행하는 노드로 제한됩니다. 필요에 따라 이러한 제약 조건을 추가로 사용자 지정할 수 있습니다.

.단계
. 라는 이름의 파일을 `nodeSelectorConfig.yaml` 만듭니다.
. 파일에 nodeSelector 옵션을 추가하고 해당 파일을 수정하여 노드 레이블을 추가하거나 변경하여 환경 요구 사항에 따라 제한합니다. 예를 들어, 다음 파일에는 기본 OS 제한이 포함되어 있지만 특정 지역 및 앱 이름도 대상으로 합니다.
+
[source, yaml]
----
nodeSelector:
  kubernetes.io/os: linux
  region: us-west
  app.kubernetes.io/name: mysql
----
. 파일의 값을 적용합니다 `nodeSelectorConfig.yaml`.
+
[source, console]
----
helm upgrade trident-protect -n trident-protect netapp-trident-protect/trident-protect -f nodeSelectorConfig.yaml --reuse-values
----
+
이렇게 하면 기본 제한 사항이 파일에 지정한 제한 사항으로 `nodeSelectorConfig.yaml` 바뀝니다.





== 일일 Trident Protect AutoSupport 번들 업로드를 비활성화합니다

필요에 따라 예약된 일일 Trident Protect AutoSupport 지원 번들 업로드를 비활성화할 수 있습니다.


NOTE: 기본적으로 Trident Protect는 클러스터 및 관리형 애플리케이션에 대한 로그, 메트릭, 토폴로지 정보 등 파트너가 개설할 수 있는 모든 NetApp 지원 사례에 도움이 되는 지원 정보를 수집합니다. Trident Protect는 이러한 지원 번들을 일일 일정에 따라 NetApp로 전송합니다. 언제든지 수동으로 수행할 수 link:trident-protect-generate-support-bundle.html["지원 번들을 생성합니다"]있습니다.

.단계
. 라는 이름의 파일을 `autosupportconfig.yaml` 만듭니다.
. 파일에 AutoSupport 옵션을 추가하고 환경 요구 사항에 따라 매개 변수를 수정합니다.
+
다음 예에서는 AutoSupport 옵션에 대한 매개 변수의 기본값을 보여 줍니다.

+
[source, yaml]
----
autoSupport:
  enabled: true
----
+
이 로 설정된 `false` 경우 `autoSupport.enabled` AutoSupport 지원 번들의 일일 업로드가 비활성화됩니다.

. 파일의 값을 적용합니다 `autosupportconfig.yaml`.
+
[source, console]
----
helm upgrade trident-protect netapp-trident-protect/trident-protect -f autosupportconfig.yaml --reuse-values
----

