---
sidebar: sidebar 
permalink: trident-protect/trident-protect-upgrade.html 
keywords: trident, protect, netapp, upgrade, new, version 
summary: Trident Protect를 최신 버전으로 업그레이드하면 새로운 기능이나 버그 수정을 활용할 수 있습니다. 
---
= Trident 프로텍트 업그레이드
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Trident Protect를 최신 버전으로 업그레이드하면 새로운 기능이나 버그 수정을 활용할 수 있습니다.

[NOTE]
====
* 24.10 버전에서 업그레이드하는 경우, 업그레이드 중 실행 중인 스냅샷이 실패할 수 있습니다. 이 실패는 향후 수동 또는 예약된 스냅샷 생성을 방해하지 않습니다. 업그레이드 중 스냅샷이 실패할 경우, 수동으로 새 스냅샷을 생성하여 애플리케이션을 보호할 수 있습니다.
+
잠재적인 오류를 방지하려면 업그레이드 전에 모든 스냅샷 일정을 비활성화했다가 나중에 다시 활성화할 수 있습니다. 하지만 이렇게 하면 업그레이드 기간 동안 예약된 스냅샷이 모두 손실될 수 있습니다.

* 개인 레지스트리 설치의 경우 대상 버전에 필요한 Helm 차트와 이미지가 개인 레지스트리에서 사용 가능한지 확인하고, 사용자 지정 Helm 값이 새 차트 버전과 호환되는지 확인하세요. 자세한 내용은 다음을 참조하세요.link:trident-protect-installation.html["개인 레지스트리에서 Trident Protect 설치"] .


====


== 1단계: 버전을 선택합니다

Trident Protect 버전은 날짜 기반 `YY.MM` 명명 규칙을 따르며, 여기서 "YY"는 연도의 마지막 두 자리 숫자이고 "MM"은 월을 나타냅니다. 도트 릴리스는 `YY.MM.X` 규칙을 따르며, 여기서 "X"는 패치 레벨을 나타냅니다. 업그레이드할 버전은 업그레이드하려는 현재 버전을 기준으로 선택합니다.

* 설치된 버전에서 4개 릴리스 이내의 대상 릴리스로 직접 업그레이드할 수 있습니다. 예를 들어 24.10(또는 24.10의 모든 마이너 버전)에서 25.10으로 직접 업그레이드할 수 있습니다.
* 4개 릴리스 기간 외의 버전에서 업그레이드하는 경우 여러 단계를 거쳐 업그레이드하십시오. link:../earlier-versions.html["이전 버전"]에서 업그레이드하는 경우 해당 버전의 업그레이드 지침을 사용하여 4개 릴리스 기간에 맞는 최신 릴리스로 업그레이드하십시오. 예를 들어 24.10을 실행 중이고 26.02으로 업그레이드하려는 경우:
+
.. 먼저 24.10에서 25.02으로 업그레이드하십시오.
.. 그다음 25.02에서 26.02으로 업그레이드하세요.






== 2단계: Trident Protect 업그레이드

Trident Protect를 업그레이드하려면 다음 단계를 수행하세요.

.단계
. Trident Helm 리포지토리를 업데이트합니다.
+
[source, console]
----
helm repo update
----
. Trident Protect CRD 업그레이드:
+

NOTE: 25.06 이전 버전에서 업그레이드하는 경우 CRD가 이제 Trident Protect Helm 차트에 포함되었으므로 이 단계가 필요합니다.

+
.. CRD 관리를 전환하려면 이 명령을 실행하세요.  `trident-protect-crds` 에게  `trident-protect` :
+
[source, console]
----
kubectl get crd | grep protect.trident.netapp.io | awk '{print $1}' | xargs -I {} kubectl patch crd {} --type merge -p '{"metadata":{"annotations":{"meta.helm.sh/release-name": "trident-protect"}}}'
----
.. Helm 비밀을 삭제하려면 이 명령을 실행하세요.  `trident-protect-crds` 차트:
+

NOTE: 제거하지 마십시오  `trident-protect-crds` Helm을 사용하여 차트를 만들면 CRD와 관련 데이터가 제거될 수 있습니다.

+
[source, console]
----
kubectl delete secret -n trident-protect -l name=trident-protect-crds,owner=helm
----


. Trident 프로텍트 업그레이드:
+
[source, console]
----
helm upgrade trident-protect netapp-trident-protect/trident-protect --version 100.2602.0 --namespace trident-protect
----
+

NOTE: 업그레이드 중에 로깅 수준을 구성하려면 다음을 추가하세요. `--set logLevel=debug` 업그레이드 명령으로. 기본 로깅 수준은 다음과 같습니다. `warn` . 디버그 로깅은 NetApp 지원팀이 로그 수준을 변경하거나 문제를 재현하지 않고도 문제를 진단하는 데 도움이 되므로 문제 해결에 권장됩니다.


