---
sidebar: sidebar 
permalink: trident-protect/trident-protect-cli.html 
keywords: trident, protect, command line utility, cli, netapp, custom, resources 
summary: protectctl 명령을 사용하여 Trident Protect 사용자 지정 리소스를 만들고 상호 작용할 수 있습니다. 
---
= Trident Protect CLI 플러그인을 설치합니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Trident 유틸리티의 확장인 Trident Protect 명령줄 플러그인을 사용하여 Trident CRS(사용자 지정 리소스)를 만들고 상호 작용할 수 있습니다 `tridentctl`.



== Trident Protect CLI 플러그인을 설치합니다

명령줄 유틸리티를 사용하기 전에 클러스터에 액세스하는 데 사용하는 시스템에 설치해야 합니다. 컴퓨터에서 x64 또는 ARM CPU를 사용하는지 여부에 따라 다음 단계를 수행합니다.

[role="tabbed-block"]
====
.Linux AMD64 CPU용 플러그인을 다운로드합니다
--
.단계
. Trident Protect CLI 플러그인 다운로드:
+
[source, console]
----
curl -L -o tridentctl-protect https://github.com/NetApp/tridentctl-protect/releases/download/25.02.0/tridentctl-protect-linux-amd64
----


--
.Linux ARM64 CPU용 플러그인을 다운로드합니다
--
.단계
. Trident Protect CLI 플러그인 다운로드:
+
[source, console]
----
curl -L -o tridentctl-protect https://github.com/NetApp/tridentctl-protect/releases/download/25.02.0/tridentctl-protect-linux-arm64
----


--
.Mac AMD64 CPU용 플러그인을 다운로드합니다
--
.단계
. Trident Protect CLI 플러그인 다운로드:
+
[source, console]
----
curl -L -o tridentctl-protect https://github.com/NetApp/tridentctl-protect/releases/download/25.02.0/tridentctl-protect-macos-amd64
----


--
.Mac ARM64 CPU용 플러그인을 다운로드합니다
--
.단계
. Trident Protect CLI 플러그인 다운로드:
+
[source, console]
----
curl -L -o tridentctl-protect https://github.com/NetApp/tridentctl-protect/releases/download/25.02.0/tridentctl-protect-macos-arm64
----


--
====
. 플러그인 바이너리에 대한 실행 권한 활성화:
+
[source, console]
----
chmod +x tridentctl-protect
----
. PATH 변수에 정의된 위치에 플러그인 바이너리를 복사합니다. 예를 `/usr/bin` 들어, 또는 `/usr/local/bin` (Elevated Privileges가 필요할 수 있음):
+
[source, console]
----
cp ./tridentctl-protect /usr/local/bin/
----
. 선택적으로 플러그인 바이너리를 홈 디렉토리의 위치로 복사할 수 있습니다. 이 경우 위치가 PATH 변수의 일부인지 확인하는 것이 좋습니다.
+
[source, console]
----
cp ./tridentctl-protect ~/bin/
----



NOTE: PATH 변수의 위치에 플러그인을 복사하면 또는 `tridentctl protect` 임의의 위치에서 플러그인을 사용할 수 `tridentctl-protect` 있습니다.



== Trident CLI 플러그인 도움말을 봅니다

내장 플러그인 도움말 기능을 사용하여 플러그인 기능에 대한 자세한 도움말을 얻을 수 있습니다.

.단계
. 도움말 기능을 사용하여 사용 지침을 봅니다.
+
[source, console]
----
tridentctl-protect help
----




== 명령 자동 완성 활성화

Trident Protect CLI 플러그인을 설치한 후 특정 명령에 대해 자동 완성 기능을 활성화할 수 있습니다.

[role="tabbed-block"]
====
.Bash 셸에 대해 자동 완성 기능을 활성화합니다
--
.단계
. 완료 스크립트 다운로드:
+
[source, console]
----
curl -L -O https://github.com/NetApp/tridentctl-protect/releases/download/25.02.0/tridentctl-completion.bash
----
. 스크립트를 포함할 홈 디렉토리에 새 디렉토리를 만듭니다.
+
[source, console]
----
mkdir -p ~/.bash/completions
----
. 다운로드한 스크립트를 디렉터리로 이동합니다 `~/.bash/completions`.
+
[source, console]
----
mv tridentctl-completion.bash ~/.bash/completions/
----
. 홈 디렉토리의 파일에 다음 줄을 추가합니다 `~/.bashrc`.
+
[source, console]
----
source ~/.bash/completions/tridentctl-completion.bash
----


--
.Z 쉘에 대한 자동 완성 기능을 활성화합니다
--
.단계
. 완료 스크립트 다운로드:
+
[source, console]
----
curl -L -O https://github.com/NetApp/tridentctl-protect/releases/download/25.02.0/tridentctl-completion.zsh
----
. 스크립트를 포함할 홈 디렉토리에 새 디렉토리를 만듭니다.
+
[source, console]
----
mkdir -p ~/.zsh/completions
----
. 다운로드한 스크립트를 디렉터리로 이동합니다 `~/.zsh/completions`.
+
[source, console]
----
mv tridentctl-completion.zsh ~/.zsh/completions/
----
. 홈 디렉토리의 파일에 다음 줄을 추가합니다 `~/.zprofile`.
+
[source, console]
----
source ~/.zsh/completions/tridentctl-completion.zsh
----


--
====
.결과
다음 쉘 로그인 시 tridentctl-protect 플러그인으로 명령 자동 완성 기능을 사용할 수 있습니다.
